import { forwardRef, type ReactNode } from 'react';
import { Text as NativeText, TextInput as NativeTextInput, type AlertButton, type AlertOptions, type TextInputProps, type TextProps } from 'react-native';

import { languageState } from '@/src/store/ui-preferences';
import { showThemedAlert } from '@/src/store/themed-alert';
import { staticChineseUICopy, staticChineseUITemplateFragments } from '@/src/generated/ui-copy';

const { useSnapshot } = require('valtio/react');

const exactEnglish: Record<string, string> = {
  '查看更新内容': 'View release notes',
  '下载 IPA': 'Download IPA',
  'Safari 下载': 'Download in Safari',
  '重新下载 IPA': 'Download IPA again',
  '选择签名 App': 'Choose signing app',
  '版本与 IPA': 'Versions and IPA',
  '连接 Sub2API': 'Connect to Sub2API',
  '连接 CLIProxyAPI': 'Connect to CLIProxyAPI',
  '独立管理 CLI 分组、Client Key、OAuth 账号池和实时配额。': 'Manage CLI groups, client keys, OAuth account pools, and live quotas independently.',
  'CLIProxyAPI 需要启用 remote-management；连接成功后只显示 CLIProxy 工作区。': 'CLIProxyAPI must enable remote-management. After connecting, only the CLIProxy workspace is shown.',
  'Web 端不会持久化 Management Key。': 'The web app does not persist the Management Key.',
  'Management Key 保存在设备安全存储中。': 'The Management Key is stored in secure device storage.',
  'CLIProxy 概览': 'CLIProxy overview',
  'CLIProxy 分组': 'CLIProxy groups',
  'CLIProxy 凭据': 'CLIProxy credentials',
  '日志与统计': 'Logs and usage',
  'CLIProxy 设置': 'CLIProxy settings',
  'CLIProxy 系统设置': 'CLIProxy system settings',
  'CLIProxy 日志与统计': 'CLIProxy logs and usage',
  '导入、导出、删除和检查单实例账号文件': 'Import, export, delete, and inspect single-instance credential files',
  '运行参数、Provider 配置与完整 YAML': 'Runtime settings, provider configuration, and complete YAML',
  '单实例日志、错误文件和 API Key 使用情况': 'Single-instance logs, error files, and API key usage',
  '插件商店': 'Plugin store',
  '运行': 'Runtime',
  '网关': 'Gateway',
  '观测': 'Observability',
  '控制': 'Control',
  '快速开始': 'Quick start',
  'AI 提供商': 'AI providers',
  '认证文件': 'Auth files',
  'OAuth 登录': 'OAuth login',
  '配额管理': 'Quota management',
  '日志查看': 'Logs',
  '配置面板': 'Config panel',
  '插件管理': 'Plugin management',
  '中心信息': 'Hub information',
  '完整 config.yaml': 'Complete config.yaml',
  'API Key 使用统计': 'API key usage',
  '运行日志': 'Runtime logs',
  '请求错误日志': 'Request error logs',
  '切换到 CLIProxyAPI': 'Switch to CLIProxyAPI',
  '切换到 Sub2API': 'Switch to Sub2API',
  '展开 CLIProxy 菜单': 'Open CLIProxy menu',
  'CLIProxyAPI 管理': 'CLIProxyAPI management',
  '独立管理 CLI 分组、Client Key、账号池与配额': 'Manage CLI groups, client keys, account pools, and quotas independently',
  '独立管理分组、Client Key、账号池与实时配额': 'Manage groups, client keys, account pools, and live quotas independently',
  '2. CLIProxy 分组与 Client Key': '2. CLIProxy groups and client keys',
  'CLIProxy 分组独立于 Sub2API；每个组用专用 Key 绑定自己的凭据池。': 'CLIProxy groups are independent from Sub2API. Each group binds its own credential pool with a dedicated key.',
  '单实例分组由 CLIProxy Group Router 插件执行': 'Single-instance grouping is enforced by the CLIProxy Group Router plugin',
  '未分组 Key、停用组或组内无可用凭据时会直接拒绝，不会回退到其他组的账号。分组数据只写入 CLIProxy 插件配置。': 'Ungrouped keys, disabled groups, and groups without an available credential are rejected without falling back to another group. Group data is stored only in CLIProxy plugin configuration.',
  '打开 CLIProxy 分组管理': 'Open CLIProxy group management',
  '已注册 Client Key': 'Registered client keys',
  '授权由 CLIProxyAPI 处理；GateNest 只轮询状态，凭据保存在 CLIProxyAPI。': 'CLIProxyAPI handles authorization. GateNest only polls status; credentials remain in CLIProxyAPI.',
  '仅在 CLIProxy 管理页面前台时定时刷新账号状态与真实配额，不在后台持续唤醒。': 'Refresh account status and live quotas only while a CLIProxy management page is in the foreground.',
  'CLIProxy 分组管理': 'CLIProxy group management',
  '单实例 · Key 到凭据池的强制路由': 'Single instance · enforced key-to-credential-pool routing',
  '插件状态': 'Plugin status',
  '分组由 CLIProxyAPI 原生 Scheduler 插件执行，不依赖 Sub2API 数据。': 'Groups are enforced by a native CLIProxyAPI scheduler plugin and do not depend on Sub2API data.',
  'CLIProxy Group Router 已生效': 'CLIProxy Group Router is active',
  '插件已发现，但尚未全局启用': 'Plugin discovered but not globally enabled',
  '存在分组配置，但插件文件缺失': 'Group configuration exists, but the plugin file is missing',
  '当前有': 'Currently',
  '个未分组 Client Key；Group Router 会拒绝这些 Key 的模型请求。': 'unassigned client keys; Group Router rejects model requests from these keys.',
  '个凭据不在统一优先级，可能在分组过滤前隐藏其他组凭据。': 'credentials are not on the shared priority tier and may hide another group before filtering.',
  '统一凭据优先级': 'Normalize credential priorities',
  '尚未安装 CLIProxy Group Router': 'CLIProxy Group Router is not installed',
  '插件目录：': 'Plugin directory: ',
  '启用 Group Router 插件': 'Enable Group Router plugin',
  '启用 Group Router？': 'Enable Group Router?',
  '启用后，尚未加入 CLIProxy 分组的 Client Key 将被拒绝。请随后立即创建分组。': 'After enabling, client keys not assigned to a CLIProxy group will be rejected. Create a group immediately afterward.',
  '新建 CLIProxy 分组': 'Create CLIProxy group',
  '编辑 CLIProxy 分组': 'Edit CLIProxy group',
  '每个组使用独立 Client Key；一个凭据默认只能属于一个组。': 'Each group uses a dedicated client key. By default, a credential can belong to only one group.',
  '分组名称': 'Group name',
  '专用 Client Key': 'Dedicated client key',
  '生成安全 Key': 'Generate secure key',
  '复制 Key': 'Copy key',
  '调度策略': 'Scheduling strategy',
  '组内凭据（至少一个）': 'Group credentials (at least one)',
  '已属于其他组': 'Assigned to another group',
  '凭据已停用': 'Credential disabled',
  'CLIProxyAPI 账号池为空，请先完成 OAuth 授权': 'The CLIProxyAPI account pool is empty. Complete OAuth authorization first.',
  '创建分组': 'Create group',
  '保存分组': 'Save group',
  '取消编辑': 'Cancel editing',
  'CLIProxy 分组列表': 'CLIProxy group list',
  '正在加载 CLIProxy 分组配置…': 'Loading CLIProxy group configuration…',
  '未分组 Key 默认拒绝；组内没有可用凭据时不会跨组回退。': 'Ungrouped keys are rejected. A group without an available credential never falls back across groups.',
  '刷新组配额': 'Refresh group quotas',
  '尚未创建 CLIProxy 分组': 'No CLIProxy groups created',
  '删除 CLIProxy 分组？': 'Delete CLIProxy group?',
  '删除后该组 Client Key 将立即失效，且不会路由到其他组。': 'The group client key will stop working immediately and will not route to another group.',
  '普通用户不能访问 CLIProxyAPI 管理密钥或账号池。': 'Standard users cannot access the CLIProxyAPI management key or account pool.',
  '1. 连接 CLIProxyAPI': '1. Connect CLIProxyAPI',
  '3. CLI 账号授权': '3. Authorize CLI accounts',
  '4. 配额与自动刷新': '4. Quotas and auto-refresh',
  '5. CLIProxyAPI 账号池': '5. CLIProxyAPI account pool',
  '需要可从本设备访问的服务地址，以及已启用远程管理的 Management Key。': 'Enter a service URL reachable from this device and a Management Key with remote management enabled.',
  'CLIProxyAPI 服务地址': 'CLIProxyAPI service URL',
  '例如：http://192.168.1.10:8317': 'Example: http://192.168.1.10:8317',
  'Web 端不会持久化 Management Key；生产环境还需要配置 Web 请求代理。': 'The web app does not persist the Management Key. Production also requires a web request proxy.',
  '保存配置': 'Save configuration',
  '保存并测试': 'Save and test',
  'CLIProxyAPI 管理接口连接成功。': 'Connected to the CLIProxyAPI management API.',
  'CLIProxyAPI 配置已保存。': 'CLIProxyAPI configuration saved.',
  '打开 CLIProxyAPI 原生管理页': 'Open the CLIProxyAPI management page',
  '正在读取 API Keys…': 'Loading API keys…',
  'CLIProxyAPI 尚未配置客户端 API Key': 'CLIProxyAPI has no client API key',
  '复制选中密钥': 'Copy selected key',
  '测试模型列表': 'Test model list',
  '模型接口可用。': 'The model endpoint is available.',
  '模型数量：': 'Model count: ',
  '生成授权会话': 'Create authorization session',
  '设备码：': 'Device code: ',
  '复制授权信息': 'Copy authorization details',
  '授权状态：': 'Authorization status: ',
  '立即刷新': 'Refresh now',
  '取消授权会话': 'Cancel authorization session',
  '自动刷新实时配额': 'Auto-refresh live quotas',
  '后刷新': 'until refresh',
  '立即刷新全部配额': 'Refresh all quotas now',
  '正在刷新账号与配额…': 'Refreshing accounts and quotas…',
  '账号状态与实时配额已刷新。': 'Account status and live quotas refreshed.',
  '刷新完成，但部分配额查询失败。': 'Refresh finished, but some quota queries failed.',
  '上次执行': 'Last run',
  '尚未查询实时配额': 'Live quotas have not been queried',
  '支持 Codex 5h/7d、Gemini CLI 模型桶和 Antigravity 模型配额。CLIProxyAPI 自身仍负责 OAuth Token 的后台自动刷新；这里刷新的是管理端展示数据。': 'Supports Codex 5h/7d, Gemini CLI model buckets, and Antigravity model quotas. CLIProxyAPI still refreshes OAuth tokens in the background; this setting refreshes management display data.',
  '查看运行时状态、真实配额，可停用凭据或清除指定凭据的配额冷却状态。': 'View runtime status and live quotas, disable credentials, or clear quota cooldown for a credential.',
  '正在读取账号池…': 'Loading account pool…',
  'CLIProxyAPI 账号池为空': 'The CLIProxyAPI account pool is empty',
  '启用凭据': 'Enable credential',
  '停用凭据': 'Disable credential',
  '清除配额冷却': 'Clear quota cooldown',
  '实时配额': 'Live quota',
  'Token 刷新：': 'Token refreshed: ',
  '下次恢复：': 'Next recovery: ',
  '重置：': 'Reset: ',
  '查询于 ': 'Queried at ',
  '尚未查询真实配额；点击“立即刷新全部配额”。': 'Live quota has not been queried. Tap “Refresh all quotas now”.',
  '已停用': 'Disabled',
  '不可用': 'Unavailable',
  '凭据：': 'Credentials: ',
  '成功 ': 'Success ',
  ' / 失败 ': ' / failed ',
  '支付订单': 'Payment orders',
  '检索支付订单、退款并处理强制退款确认': 'Search orders, issue refunds, and confirm forced refunds',
  '检索订单': 'Search orders',
  '支持订单号、用户和支付状态筛选。': 'Filter by order number, user, or payment status.',
  '订单号 / 用户': 'Order number / user',
  '人机验证': 'Human verification',
  '与官方一致：Turnstile、腾讯天御和阿里云验证码三选一；关闭表示不启用验证码。': 'As in the official console, choose Turnstile, Tencent Captcha, Aliyun Captcha, or disable verification.',
  '腾讯天御': 'Tencent Captcha',
  '阿里云 2.0': 'Aliyun Captcha 2.0',
  '服务地域': 'Service region',
  '中国内地': 'Mainland China',
  '新加坡': 'Singapore',
  'Codex 客户端身份': 'Codex client identity',
  '自动跟随官方稳定版本；自定义 UA 只保留客户端和系统指纹，版本段由服务端重建。': 'Follow the official stable version automatically. A custom UA keeps only client and system fingerprints; the server rebuilds its version segment.',
  '每 6 小时自动同步稳定版本': 'Sync stable version every 6 hours',
  '当前版本：': 'Current version: ',
  '最近同步：': 'Last synced: ',
  '手动版本覆盖（可选）': 'Manual version override (optional)',
  'OpenAI Codex User-Agent（可选）': 'OpenAI Codex User-Agent (optional)',
  '保存系统设置': 'Save system settings',
  '系统设置已保存。': 'System settings saved.',
  '推理强度策略': 'Reasoning effort policy',
  'OpenAI 与复合分组支持限制最大推理强度，并将客户端传入的推理强度精确映射到服务端允许值。': 'OpenAI and composite groups can cap the maximum reasoning effort and map client-provided effort values to server-approved values.',
  '推理强度上限': 'Maximum reasoning effort',
  '精确映射（逗号或换行分隔）': 'Exact mappings (comma or newline separated)',
  '例如：xhigh=high, max=high': 'Example: xhigh=high, max=high',
  '查询成功': 'Query complete',
  '查询失败': 'Query failed',
  '已获取并保存最新重置次数。': 'The latest reset allowance was fetched and cached.',
  '已获取最新重置次数，但服务端缓存未能保存。': 'The latest reset allowance was fetched, but the server could not cache it.',
  '重置完成（有警告）': 'Reset completed with a warning',
  '重置成功': 'Reset complete',
  '重置失败': 'Reset failed',
  '订单号或用户邮箱': 'Order number or user email',
  '全部状态': 'All statuses',
  '已支付': 'Paid',
  '已退款': 'Refunded',
  '部分退款': 'Partially refunded',
  '退款中': 'Refund pending',
  '退款失败': 'Refund failed',
  '订单金额': 'Order amount',
  '退款金额': 'Refund amount',
  '支付方式': 'Payment method',
  '退款': 'Refund',
  '查询退款': 'Check refund',
  '发起退款': 'Issue refund',
  '退款原因': 'Refund reason',
  '同步扣减用户余额': 'Deduct the refunded amount from the user balance',
  '强制退款确认': 'Confirm forced refund',
  '支付平台已退款，但本地状态或余额更新失败。再次提交将强制完成本地退款状态，请确认后继续。': 'The payment platform refunded the order, but the local status or balance update failed. Submitting again will force the local refund state. Confirm to continue.',
  '强制完成退款': 'Force-complete refund',
  '退款成功': 'Refund complete',
  '退款请求已提交。': 'The refund request was submitted.',
  '暂未找到支付订单。': 'No payment orders found.',
  '支付金额': 'Paid amount',
  '订单退款': 'Refund order',
  '请填写退款原因': 'Enter a refund reason',
  '同时扣减用户余额/订阅': 'Deduct user balance or subscription',
  '余额不足时，服务端会要求二次强制确认；App 不会自动强制退款。': 'If the balance is insufficient, the server requires a second confirmation. The app never forces a refund automatically.',
  '提交退款': 'Submit refund',
  '暂无支付订单': 'No payment orders',
  '需要强制确认': 'Force confirmation required',
  '用户余额不足，继续退款可能产生负余额。': 'The user balance is insufficient. Continuing may create a negative balance.',
  '强制退款': 'Force refund',
  '退款处理完成': 'Refund processed',
  '订单退款状态已更新。': 'The order refund status was updated.',
  '退款状态已更新': 'Refund status updated',
  '退款已完成。': 'The refund is complete.',
  '退款仍在处理中。': 'The refund is still processing.',
  '概览': 'Dashboard',
  '仪表盘': 'Dashboard',
  '用户': 'Users',
  '账号': 'Accounts',
  '分组': 'Groups',
  '服务器': 'Server',
  '设置': 'Settings',
  '保存': 'Save',
  '取消': 'Cancel',
  '删除': 'Delete',
  '编辑': 'Edit',
  '创建': 'Create',
  '新建': 'New',
  '复制': 'Copy',
  '关闭': 'Close',
  '完成': 'Done',
  '确认': 'Confirm',
  '返回': 'Back',
  '搜索': 'Search',
  '刷新': 'Refresh',
  '刷新成功': 'Refresh complete',
  '刷新失败': 'Refresh failed',
  '暂时无法刷新服务端版本': 'Unable to refresh the server version right now.',
  '账号状态、今日统计和实时额度已刷新。': 'Account status, today’s usage, and live quota have been refreshed.',
  '每 5 分钟自动检查 GitHub Release；下拉页面也可以重新检查。': 'Checks GitHub Releases every 5 minutes. Pull down to check now.',
  '额度刷新成功': 'Quota refreshed',
  '额度刷新失败': 'Quota refresh failed',
  '已获取该账号的最新额度数据。': 'The latest quota data is now available.',
  '请稍后重试。': 'Try again later.',
  'Web 端无法发起请求。请使用 npm run web 启动，或配置可用的 Web 代理。': 'The web app could not send the request. Start it with npm run web or configure a working web proxy.',
  'Web 代理无法连接 Sub2API 服务，请检查服务地址、HTTPS 证书和网络可达性。': 'The web proxy could not reach the Sub2API server. Check the server URL, HTTPS certificate, and network access.',
  'Web 端无法连接模型服务，请重新启动 Web 或检查代理配置。': 'The web app could not reach the model service. Restart the web app or check the proxy configuration.',
  'Web 代理无法连接模型服务，请检查 Base URL、HTTPS 证书和网络。': 'The web proxy could not reach the model service. Check the Base URL, HTTPS certificate, and network.',
  '7 天额度已用完，账号默认自动停用；手动启用时可选择强制启用。': 'The 7-day quota is exhausted, so this account is disabled by default. You can force-enable it manually.',
  '强制启用账号': 'Force-enable account',
  '强制启用': 'Force enable',
  '强制启用成功': 'Force enabled',
  '强制启用失败': 'Force enable failed',
  '启用成功': 'Account enabled',
  '启用失败': 'Enable failed',
  '停用成功': 'Account disabled',
  '停用失败': 'Disable failed',
  '账号已启用。': 'The account is enabled.',
  '账号已停用。': 'The account is disabled.',
  '账号已强制启用；在额度恢复前，请留意请求失败或限流状态。': 'The account was force-enabled. Watch for request failures or rate limits until the quota recovers.',
  '服务器未返回错误详情，请稍后重试。': 'The server returned no error details. Try again later.',
  '该账号 7 天额度已用完，强制启用后仍可能请求失败或触发限流。是否继续？': 'This account has exhausted its 7-day quota. Requests may still fail or be rate-limited after force-enabling it. Continue?',
  '服务器返回的不是有效 JSON，请检查服务地址是否填写正确。': 'The server did not return valid JSON. Check that the server URL is correct.',
  '重试': 'Retry',
  '查询重置': 'Check resets',
  '可用次数：': 'Available: ',
  '当前没有可用次数，已禁用重置。': 'No resets available. Reset is disabled.',
  '启用': 'Enable',
  '停用': 'Disable',
  '隐藏': 'Hide',
  '显示': 'Show',
  '清除': 'Clear',
  '详情': 'Details',
  '收起': 'Collapse',
  '展开': 'Expand',
  '成功': 'Success',
  '失败': 'Failed',
  '正常': 'Healthy',
  '异常': 'Abnormal',
  '等待中': 'Queued',
  '执行中': 'Running',
  '处理中': 'Processing',
  '已完成': 'Completed',
  '已取消': 'Canceled',
  '已跳过': 'Skipped',
  '暂无数据': 'No data',
  '暂无记录': 'No records',
  '加载中…': 'Loading…',
  '保存中…': 'Saving…',
  '提交中…': 'Submitting…',
  '不限': 'Unlimited',
  '无': 'None',
  '全部': 'All',
  '是': 'Yes',
  '否': 'No',
  '中文': 'Chinese',
  '英文': 'English',
  '深色模式': 'Dark mode',
  '语言': 'Language',
  '退出账号': 'Sign out',
  '当前登录': 'Current session',
  'Admin Key 管理员': 'Admin Key administrator',
  '已登录用户': 'Signed-in user',
  '普通用户': 'User',
  '管理员': 'Administrator',
  '管理中心': 'Management center',
  '用户管理': 'User management',
  '账号管理': 'Account management',
  '账号操作': 'Account data',
  '导入和导出官方兼容的账号 JSON 数据': 'Import or export official-compatible account JSON',
  '导入和导出 Sub2API 官方兼容的账号 JSON 数据': 'Import or export Sub2API-compatible account JSON',
  '需要管理员权限': 'Administrator access required',
  '普通用户不能读取或导入服务端账号凭据。': 'Standard users cannot read or import server account credentials.',
  '返回更多管理': 'Back to more administration',
  '敏感数据': 'Sensitive data',
  '导出的 JSON 包含账号凭据，选择包含代理时还可能包含代理密码。请勿发送到不可信设备、群聊或网盘。': 'Exported JSON contains account credentials and may include proxy passwords. Keep it off untrusted devices, chats, and cloud drives.',
  '导出账号': 'Export accounts',
  '从当前服务器导出全部账号，文件结构与 Sub2API Web 管理端一致。': 'Export every account from this server using the Sub2API Web format.',
  '包含关联代理': 'Include linked proxies',
  '默认开启；关闭后请求会携带 include_proxies=false。': 'On by default. Turning it off sends include_proxies=false.',
  '导出 JSON': 'Export JSON',
  '导出账号数据？': 'Export account data?',
  '继续导出': 'Continue export',
  '导出成功': 'Export complete',
  '导出完成，有账号被跳过': 'Export complete with skipped accounts',
  '已打开系统保存/分享面板。请将 JSON 文件保存到可信位置。': 'The save/share sheet is open. Store the JSON file in a trusted location.',
  '官方规则会排除不持有独立凭据的 Spark 影子账号，并在导出完成后显示跳过数量。': 'Official rules exclude Spark shadow accounts without independent credentials and report the skipped count.',
  '导入账号': 'Import accounts',
  '支持选择一个或多个官方 JSON 文件；多文件会在本地校验后合并导入。': 'Choose one or more official JSON files. Multiple files are validated and merged locally.',
  '选择 JSON 文件': 'Choose JSON files',
  '校验 type、version、accounts 和 proxies': 'Validate type, version, accounts, and proxies',
  '确认导入': 'Confirm import',
  '确认导入账号数据？': 'Import account data?',
  '导入成功': 'Import complete',
  '导入完成，但有失败': 'Import completed with errors',
  '导入结果': 'Import result',
  '选择文件失败': 'Could not select files',
  '已忽略非 JSON 文件': 'Ignored non-JSON files',
  '当前设备不支持系统文件分享': 'File sharing is not available on this device',
  '按官方逻辑跳过默认分组自动绑定（skip_default_group_bind=true）。': 'Official behavior skips automatic default-group binding (skip_default_group_bind=true).',
  '若服务器启用了 Step-up，导出可能要求额外验证；Admin Key 模式可能被服务端拒绝，请按服务器安全策略使用管理员邮箱登录。': 'When Step-up is enabled, export may require extra verification. Admin Key mode can be rejected; use an administrator email session as required by the server policy.',
  '分组管理': 'Group management',
  '代理管理': 'Proxy management',
  'IP 管理': 'IP management',
  'API 密钥': 'API keys',
  '使用记录': 'Usage logs',
  '运维监控': 'Operations monitor',
  '实时概览': 'Live overview',
  '请求详情': 'Requests',
  '系统日志': 'System logs',
  '运维设置': 'Ops settings',
  '监控范围': 'Monitoring scope',
  '使用官方 Ops 时间、平台、分组和查询模式参数': 'Uses the official Ops time, platform, group, and query-mode parameters.',
  '全部平台': 'All platforms',
  '全部分组': 'All groups',
  '分组 ID（可选）': 'Group ID (optional)',
  '输入未显示在上方的分组 ID': 'Enter a group ID not shown above',
  '健康评分': 'Health score',
  '服务健康度': 'Service health',
  '官方服务端评分 · 业务健康 70% + 基础设施 30%': 'Official server score · 70% business + 30% infrastructure',
  '业务健康': 'Business health',
  '基础设施': 'Infrastructure',
  '权重': 'Weight',
  '等待数据': 'Waiting for data',
  '待机': 'Idle',
  '健康': 'Healthy',
  '良好': 'Good',
  '需关注': 'Needs attention',
  '真实扣分与风险来源': 'Real deductions and risk sources',
  '请求错误正在扣分': 'Request errors are reducing the score',
  '；官方规则超过 1% 开始扣分，达到 10% 时该项为 0。': '; the official score starts deducting above 1%, and this component reaches zero at 10%.',
  '上游错误正在扣分': 'Upstream errors are reducing the score',
  '；优先检查异常账号、限流和代理连通性。': '; check unhealthy accounts, rate limits, and proxy connectivity first.',
  '首 Token 延迟过高': 'First-token latency is too high',
  'TTFT P99 为': 'TTFT P99 is',
  'ms；超过 1 秒开始扣分，3 秒及以上该项为 0。': 'ms; deductions start above 1 second, and this component reaches zero at 3 seconds.',
  '数据库连接异常': 'Database connection failure',
  '数据库故障会直接把存储健康降为 0，需要在服务器侧检查数据库连接和资源。': 'A database failure reduces storage health to zero. Check the database connection and server resources.',
  'Redis 连接异常': 'Redis connection failure',
  'Redis 故障会把存储健康降为 50，需要检查 Redis 服务和连接池。': 'A Redis failure reduces storage health to 50. Check the Redis service and connection pool.',
  '服务器资源压力较高': 'High server resource pressure',
  '；应降低并发或扩容服务器。': '; reduce concurrency or scale the server.',
  '后台任务失败或超过 15 分钟未成功': 'Background jobs failed or have not succeeded for 15 minutes',
  '账号池存在不可用账号': 'The account pool contains unavailable accounts',
  '个；请恢复可恢复账号，并停用持续失败的账号。': 'accounts; recover eligible accounts and disable accounts that keep failing.',
  '仍有活动告警': 'Active alerts remain',
  '条告警尚未处理。': 'alerts are unresolved.',
  '服务端返回低分但明细不足': 'The server returned a low score without enough details',
  '当前响应没有包含明确的扣分指标，请从错误日志确认服务器端故障原因。': 'The response does not include a clear deduction metric. Check the error logs for the server-side cause.',
  '查看失败请求': 'View failed requests',
  '处理异常账号': 'Handle unhealthy accounts',
  '检测代理质量': 'Test proxy quality',
  '处理活动告警': 'Handle active alerts',
  '查看错误日志': 'View error logs',
  '查看最近 5 分钟': 'View the last 5 minutes',
  '刷新评分': 'Refresh score',
  '刷新中…': 'Refreshing…',
  '当前窗口没有请求，官方规则按待机状态返回 100 分。': 'There are no requests in this window. The official idle rule returns a score of 100.',
  '当前指标未发现明显扣分项。': 'No clear score deductions were found in the current metrics.',
  '修复后分数按所选统计窗口重新计算；1h/24h 仍包含之前的错误，使用 5m 窗口可以更快验证恢复是否真实生效。': 'After a fix, the score is recalculated for the selected window. The 1h and 24h windows still include earlier errors; use 5m to verify recovery sooner.',
  '活动告警': 'Active alerts',
  '请求总数': 'Requests',
  '请求错误率': 'Request error rate',
  '上游错误率': 'Upstream error rate',
  '实时流量': 'Live traffic',
  '1 分钟实时窗口，每 5 秒更新': '1-minute live window, updated every 5 seconds.',
  'QPS 当前': 'Current QPS',
  'TPS 当前': 'Current TPS',
  'QPS 峰值 / 平均': 'QPS peak / average',
  'TPS 峰值 / 平均': 'TPS peak / average',
  '耗时与 TTFT': 'Latency and TTFT',
  '官方 Ops 百分位统计': 'Official Ops percentile metrics',
  '请求耗时': 'Request latency',
  '请求趋势': 'Request trend',
  '吞吐趋势': 'Throughput trend',
  '账号切换趋势': 'Account switch trend',
  '账号池切换次数': 'Account-pool switches',
  '延迟分布': 'Latency distribution',
  '错误趋势': 'Error trend',
  '错误分布': 'Error distribution',
  '并发与队列': 'Concurrency and queue',
  '实时并发状态': 'Live concurrency',
  '服务端并发监控未启用': 'Server concurrency monitoring is disabled.',
  '暂无并发数据': 'No concurrency data',
  '账号可用性': 'Account availability',
  '平台账号池状态': 'Platform account-pool status',
  '服务端可用性监控未启用': 'Server availability monitoring is disabled.',
  '暂无账号池数据': 'No account-pool data',
  '系统状态': 'System status',
  'CPU、内存、数据库、Redis、队列与后台任务': 'CPU, memory, database, Redis, queue, and background jobs',
  '服务端暂未返回系统指标': 'The server has not returned system metrics.',
  '平台吞吐': 'Platform throughput',
  '按平台拆分': 'Breakdown by platform',
  '分组吞吐': 'Group throughput',
  '请求量最高的分组': 'Top groups by request volume',
  'OpenAI Token 性能': 'OpenAI token performance',
  '按模型统计输出速度和首 Token 延迟': 'Output speed and first-token latency by model',
  '暂无 OpenAI Token 统计': 'No OpenAI token metrics',
  '请求检索': 'Request search',
  '官方 Ops 请求明细': 'Official Ops request details',
  '请求 ID、模型或消息': 'Request ID, model, or message',
  '当前筛选下没有请求': 'No requests match the current filters.',
  '收起详情': 'Hide details',
  '查看详情': 'View details',
  '日志写入健康': 'Log ingestion health',
  '服务端结构化日志队列': 'Server structured-log queue',
  '丢弃 / 失败': 'Dropped / failed',
  '平均写入延迟': 'Average write latency',
  '日志筛选': 'Log filters',
  '消息、组件或 Request ID': 'Message, component, or Request ID',
  '仪表盘设置': 'Dashboard settings',
  '与官方 Ops 高级设置保持一致': 'Aligned with official Ops advanced settings',
  '自动刷新': 'Auto refresh',
  '按服务端保存的间隔刷新': 'Refresh using the server-saved interval',
  '展示告警事件': 'Show alert events',
  '在运维监控中加载告警': 'Load alerts in operations monitoring',
  '展示 OpenAI Token 统计': 'Show OpenAI token metrics',
  '加载按模型性能统计': 'Load per-model performance metrics',
  '指标阈值': 'Metric thresholds',
  '用于 SLA、TTFT 和错误率告警着色': 'Used for SLA, TTFT, and error-rate alert colors',
  'SLA 最低百分比': 'Minimum SLA percent',
  'TTFT P99 上限（ms）': 'TTFT P99 limit (ms)',
  '请求错误率上限（%）': 'Request error-rate limit (%)',
  '上游错误率上限（%）': 'Upstream error-rate limit (%)',
  '保存运维设置': 'Save Ops settings',
  '运维监控设置已更新。': 'Operations monitoring settings were updated.',
  '错误中心': 'Error center',
  '审计日志': 'Audit logs',
  '构建中心': 'Build center',
  '构建与同步': 'Build & sync',
  'AI 助手': 'AI assistant',
  'AI 配置': 'AI settings',
  '悬浮助手': 'Floating assistant',
  '管理悬浮助手、模型与修复配置': 'Manage the floating assistant, models, and repair settings.',
  '加载当前账号配置': 'Load current account configuration',
  '从当前登录的 Sub2API 服务器加载 OpenAI Base URL 和当前用户的活动密钥；多个密钥可选择其中一个。': 'Load the OpenAI Base URL and active keys for the current user from the signed-in Sub2API server. Select one when multiple keys are available.',
  '当前服务器 OpenAI Base URL': 'Current server OpenAI Base URL',
  '尚未连接 Sub2API 服务器': 'No Sub2API server connected',
  '正在加载当前账号密钥…': 'Loading current account keys…',
  '当前账号没有可用的活动密钥': 'No active keys are available for this account',
  '当前登录模式无法加载用户密钥': 'The current sign-in mode cannot load user keys',
  '刷新当前账号密钥': 'Refresh current account keys',
  '已选择': 'Selected',
  '选择': 'Select',
  '使用悬浮助手当前会话中的最新问题生成修复方案；创建 Draft PR 前仍会确认。': 'Generate a fix from the latest issue in the floating conversation. Draft PR creation still requires confirmation.',
  '删除历史对话': 'Delete conversation',
  '助手设置': 'Assistant settings',
  '收起助手设置': 'Hide assistant settings',
  '悬浮助手外观': 'Floating assistant appearance',
  '选择助手外观': 'Choose assistant appearance',
  '猫咪': 'Cat',
  '小狗': 'Dog',
  '狐狸': 'Fox',
  '兔子': 'Rabbit',
  '小精灵': 'Sprite',
  '迪迦奥特曼': 'Ultraman Tiga',
  '猪猪侠': 'GG Bond',
  '推理强度': 'Reasoning effort',
  '显示悬浮助手': 'Show floating assistant',
  'GitHub 配置': 'GitHub settings',
  '关于': 'About',
  '关于应用': 'About app',
  '版本、在线更新与开源信息': 'Version, online updates, and open-source information',
  '版本': 'Version',
  '升级提示': 'Update status',
  '自动检查 GitHub Release；下拉页面也可以重新检查。': 'Checks GitHub Releases automatically. Pull down to check again.',
  '正在检查 GitHub Release…': 'Checking GitHub Releases…',
  '暂时无法检查新版本': 'Unable to check for updates',
  '仓库尚未发布正式版本': 'No release is available yet',
  '当前已是最新版本': 'You are up to date',
  '重新检查版本': 'Check again',
  '正在检查…': 'Checking…',
  '打开 Release 页面': 'Open release page',
  '当前版本没有可用的 Android APK': 'No Android APK is available for this release',
  'App 内安装仅支持 Android': 'In-app installation is available on Android only',
  '无法访问下载目录': 'Unable to access the download directory',
  'APK 下载未完成，请重试': 'APK download did not finish. Try again.',
  '正在打开安装程序…': 'Opening installer…',
  '在 App 内下载并安装': 'Download and install in app',
  '将下载：': 'Download: ',
  '下载完成，正在打开系统安装程序': 'Download complete. Opening the system installer.',
  '正在下载更新': 'Downloading update',
  '所有 App 版本的升级提示已关闭，手动检查和下载仍可使用。': 'All app update alerts are off. Manual checks and downloads remain available.',
  '重新开启所有升级提示': 'Enable all update alerts',
  '已忽略此版本的升级提示：': 'Ignored update alert: ',
  '忽略此版本': 'Ignore this version',
  '关闭全部提示': 'Disable all alerts',
  '恢复此版本提示': 'Restore this version alert',
  'Expo 在线更新': 'Expo online update',
  '仅更新 JavaScript 与资源；原生依赖、权限或 Expo SDK 变化仍需安装新 APK。': 'Updates JavaScript and assets only. Native dependencies, permissions, or Expo SDK changes require a new APK.',
  '正式包启用 EAS Update 后，可以在这里下载在线更新并重启应用完成升级。': 'With EAS Update enabled, production builds can download an update here and restart to apply it.',
  '检查 Expo 在线更新': 'Check Expo update',
  '已是最新版本': 'You are up to date',
  '没有可用的 Expo 在线更新。': 'No Expo update is available.',
  '更新已下载': 'Update downloaded',
  '是否立即重新启动并应用更新？': 'Restart now to apply the update?',
  '稍后': 'Later',
  '立即重启': 'Restart now',
  '当前开发环境未启用 Expo 在线更新': 'Expo online updates are disabled in this development environment',
  '开源项目': 'Open source',
  '代码、发布版本、问题反馈与许可证信息。': 'Source code, releases, issue reporting, and license information.',
  '开源仓库': 'Source repository',
  '版本与 APK': 'Releases and APKs',
  '查看全部 GitHub Releases': 'View all GitHub Releases',
  '问题反馈': 'Issue tracker',
  '提交 Bug、建议或兼容性问题': 'Report bugs, suggestions, or compatibility issues',
  '查看本项目开源许可证': 'View the project license',
  '灵感来源': 'Acknowledgements',
  '感谢 ckken/sub2api-mobile 的开源成果': 'Thanks to the open-source work of ckken/sub2api-mobile',
  '更新与安全说明': 'Update and security notes',
  '请只从本项目 GitHub Releases 或你信任的构建渠道安装 APK。更新前建议保留服务器地址与登录信息。': 'Install APKs only from this project\'s GitHub Releases or a trusted build channel. Keep your server and sign-in details before updating.',
  'Android 会在 App 内下载 APK 并显示进度，完成后由系统安装程序确认安装；签名不一致时需要先卸载旧版。App 无法静默覆盖安装。': 'Android downloads the APK in the app with progress, then opens the system installer for confirmation. A signature mismatch requires uninstalling the old version. Silent replacement is not supported.',
  '查看安全策略': 'View security policy',
  '无法打开链接': 'Unable to open link',
  '更多管理': 'More administration',
  '当前登录、语言与 Sub2API 高级管理功能': 'Session, language, and advanced Sub2API management',
  '系统设置': 'System settings',
  '系统维护': 'System maintenance',
  '公告管理': 'Announcements',
  '订阅管理': 'Subscriptions',
  '兑换码': 'Redeem codes',
  '推广码': 'Promo codes',
  '备份管理': 'Backups',
  '备份与数据管理': 'Backup & data management',
  '操作审计': 'Audit trail',
  '全部 API': 'All APIs',
  '推广返利': 'Affiliate rewards',
  '渠道监控': 'Channel monitors',
  '编辑渠道': 'Edit channel',
  '新增渠道': 'Add channel',
  '合规确认': 'Compliance confirmation',
  'OAuth 授权': 'OAuth authorization',
  '优惠码': 'Promo codes',
  '提示词审计': 'Prompt audit',
  '新增代理': 'Add proxy',
  '编辑代理': 'Edit proxy',
  '风控中心': 'Risk control',
  '用户属性': 'User attributes',
  'API Key 分组': 'API key group',
  '用户详情': 'User details',
  '编辑用户': 'Edit user',
  '账号清单': 'Account list',
  '添加账号': 'Add account',
  '添加用户': 'Add user',
  '渠道管理': 'Channels',
  '流量策略': 'Traffic policies',
  '风险控制': 'Risk control',
  '定时测试': 'Scheduled tests',
  '账号定时刷新': 'Scheduled account refresh',
  '新建对话': 'New conversation',
  '历史对话': 'Conversation history',
  '完整对话': 'Full chat',
  '清空对话': 'Clear chat',
  '发送消息': 'Send message',
  '构建方式': 'Build provider',
  'GitHub 原生 APK': 'GitHub native APK',
  'EAS 云构建': 'EAS cloud build',
  '构建进度': 'Build progress',
  '安装依赖': 'Install dependencies',
  '配置': 'Configuration',
  '名称': 'Name',
  '状态': 'Status',
  '类型': 'Type',
  '平台': 'Platform',
  '模型': 'Model',
  '请求': 'Request',
  '请求模型': 'Requested model',
  '上游模型': 'Upstream model',
  '请求类型': 'Request type',
  '服务等级': 'Service tier',
  '计费模式': 'Billing mode',
  '端点': 'Endpoints',
  '时间': 'Time',
  '费用': 'Cost',
  '总耗时': 'Duration',
  '首字耗时': 'TTFT',
  '邮箱': 'Email',
  '密码': 'Password',
  '服务地址': 'Server URL',
  '当前用户创建的密钥': 'Keys created by the current user',
  '记住登录信息': 'Remember login information',
  '已记住的账号': 'Remembered accounts',
  '登录并连接': 'Sign in and connect',
  '邮箱密码': 'Email & password',
  '连接你的服务': 'Connect to your service',
  '支持邮箱密码登录和 Admin Key 管理模式。普通用户登录后只显示自助功能。': 'Sign in with email and password or use Admin Key administration mode. Standard users only see self-service features.',
  '退出后仍可从账号下拉列表快速登录': 'Use the account dropdown to sign in again after signing out',
  '切换后立即生效，并在下次启动时保持。': 'Changes apply immediately and persist across app launches.',
  '凭据保存在设备安全存储中，不会上传到移动端项目。': 'Credentials are stored securely on this device and are never uploaded to the mobile project.',
  '勾选后凭据保存在设备安全存储中，不会上传到移动端项目。': 'When enabled, credentials are stored securely on this device and are never uploaded.',
  'Web 端不持久化密码和 Admin Key。': 'The web app does not persist passwords or Admin Keys.',
  'Web 端不会保存密码或 Admin Key': 'The web app does not save passwords or Admin Keys',
  '登录页支持“网址 + 邮箱密码”和“网址 + Admin Key”两种方式。': 'The login page supports server URL with email/password or server URL with Admin Key.',
  '长按菜单并拖到目标位置，松手后自动保存。': 'Press and hold a menu item, drag it to the target position, then release to save.',
  '长按悬浮球可以关闭；关闭后可在这里重新打开。': 'Press and hold the floating assistant to disable it; enable it again here.',
  '长按悬浮助手可移动；靠边松手后会自动半隐藏。': 'Press and hold to move it. Release near an edge to dock it partially off-screen.',
  '关闭后可在这里重新打开。': 'Turn it back on here.',
  '在这里控制开关和外观；长按可移动，靠边松手后会自动半隐藏。': 'Control visibility and appearance here. Hold to move; release near an edge to dock.',
  '长按移动位置，靠边松手后会半隐藏；长按后点击右上角 × 可以关闭。': 'Press and hold to move it. Release near an edge to dock it partially off-screen. Tap the × after a long press to disable it.',
  '点击下拉快速登录': 'Open the dropdown for quick sign-in',
  '请输入服务器地址': 'Enter the server URL',
  '请输入邮箱和密码': 'Enter your email and password',
  '请输入 Admin Key': 'Enter the Admin Key',
  '正在检测当前服务是否可用...': 'Checking whether the current service is available…',
  '退出账号 / 更换登录方式': 'Sign out / change login method',
  '退出账号 / 切换账号': 'Sign out / switch account',
  '退出后可在登录页选择已记住的账号，或输入新的账号信息。': 'After signing out, choose a remembered account or enter another account on the sign-in page.',
  '这里只展示当前登录的服务器信息。如需新增或切换账号，请先退出，再到登录页选择或输入账号。': 'Only the current server session is shown here. To add or switch accounts, sign out and use the sign-in page.',
  '没有找到可作为默认账号的管理员。': 'No administrator account is available as the default account.',
  '当前账号还没有 API 密钥': 'This account has no API keys yet',
  '点击上方蓝色加号创建第一个密钥。': 'Tap the blue plus button above to create the first key.',
  '请调整搜索关键词。': 'Try a different search term.',
  '请立即复制保存。服务器可能只在创建时返回完整密钥。': 'Copy and save it now. The server may return the complete key only once.',
  '选择卡片中要显示的请求状态和诊断字段。': 'Select the request status and diagnostic fields shown on each card.',
  '按计划刷新启用账号的上游凭据': 'Refresh upstream credentials for enabled accounts on schedule',
  '根据队列和环境选择 EAS 或 GitHub 原生 APK 构建': 'Choose EAS or GitHub native APK builds based on queue and environment',
  '多会话 · Markdown · 页面级模型与推理设置': 'Multiple conversations · Markdown · Per-page model and reasoning settings',
  '查看 OpenAI 端点与当前账号的访问密钥': 'View the OpenAI endpoint and access keys for the current account',
  '集中查看所有密钥的访问白名单与黑名单': 'View access allowlists and blocklists for all keys',
  '打开用户管理': 'Open user management',
  '复制成功': 'Copied',
  '复制失败': 'Copy failed',
  '操作成功': 'Operation successful',
  '操作失败': 'Operation failed',
  '删除成功': 'Deleted',
  '删除失败': 'Delete failed',
  '保存成功': 'Saved',
  '保存失败': 'Save failed',
  '创建成功': 'Created',
  '登录失败': 'Sign-in failed',
  '恢复默认': 'Restore defaults',
  '账号状态已恢复。': 'Account status restored.',
  '账号状态恢复失败，请稍后重试。': 'Could not restore the account status. Try again later.',
  '知道了': 'Got it',
  '自定义状态显示': 'Customize displayed fields',
  '自定义菜单': 'Customize menu',
  '设为默认启动页面': 'Set as default start page',
  '取消默认启动页面': 'Clear default start page',
  '打开网站': 'Open website',
};

const phraseEnglish: Record<string, string> = {
  '当前服务端': 'current server',
  '当前账号': 'current account',
  '当前用户': 'current user',
  '当前页面': 'current page',
  '创建时间': 'created at',
  '更新时间': 'updated at',
  '最后更新': 'last updated',
  '登录信息': 'login information',
  '登录方式': 'sign-in method',
  '快速登录': 'quick sign-in',
  '安全存储': 'secure storage',
  '服务地址': 'server URL',
  '邮箱密码': 'email and password',
  '访问密钥': 'access key',
  '密钥名称': 'key name',
  '密钥状态': 'key status',
  '白名单': 'allowlist',
  '黑名单': 'blocklist',
  '所属分组': 'assigned group',
  '不绑定分组': 'no group',
  '请求记录': 'request records',
  '调用记录': 'usage records',
  '请求错误': 'request errors',
  '上游错误': 'upstream errors',
  '输入 Token': 'input tokens',
  '输出 Token': 'output tokens',
  '缓存写入': 'cache write',
  '缓存读取': 'cache read',
  '标准费用': 'standard cost',
  '实际费用': 'actual cost',
  '平均耗时': 'average latency',
  '上游账号': 'upstream account',
  '模型测试': 'model test',
  '质量检测': 'quality check',
  '连通测试': 'connectivity test',
  '定时刷新': 'scheduled refresh',
  '立即刷新': 'refresh now',
  '批量删除': 'delete selected',
  '批量操作': 'bulk actions',
  '全部删除': 'delete all',
  '打开浏览器': 'open browser',
  '打开任务': 'open run',
  '下载 APK': 'download APK',
  '构建 APK': 'build APK',
  '构建': 'build',
  '开始构建': 'start build',
  '构建结果': 'build result',
  '构建记录': 'build history',
  '构建仓库': 'build repository',
  '分支或标签': 'branch or tag',
  '原生构建': 'native build',
  '云端执行': 'runs in the cloud',
  '账号列表': 'account list',
  '用户列表': 'user list',
  '服务器列表': 'server list',
  '新增账号': 'add account',
  '添加账号': 'add account',
  '添加用户': 'add user',
  '新建密钥': 'create key',
  '编辑密钥': 'edit key',
  '删除密钥': 'delete key',
  '复制密钥': 'copy key',
  '搜索名称': 'search name',
  '恢复默认': 'restore defaults',
  '暂无': 'no',
  '正在': '',
  '已保存': 'saved',
  '已删除': 'deleted',
  '已创建': 'created',
  '已启用': 'enabled',
  '已停用': 'disabled',
  '请选择': 'please select',
  '请输入': 'please enter',
  '请先': 'please first',
  '请检查': 'please check',
  '点击': 'tap',
  '长按': 'press and hold',
  '打开': 'open',
  '选择': 'select',
  '切换': 'switch',
  '保存': 'save',
  '删除': 'delete',
  '编辑': 'edit',
  '创建': 'create',
  '新建': 'new',
  '复制': 'copy',
  '关闭': 'close',
  '取消': 'cancel',
  '确认': 'confirm',
  '返回': 'back',
  '搜索': 'search',
  '刷新': 'refresh',
  '启用': 'enable',
  '停用': 'disable',
  '隐藏': 'hide',
  '显示': 'show',
  '成功': 'success',
  '失败': 'failed',
  '错误': 'error',
  '用户': 'user',
  '账号': 'account',
  '分组': 'group',
  '密钥': 'key',
  '服务器': 'server',
  '代理': 'proxy',
  '模型': 'model',
  '平台': 'platform',
  '状态': 'status',
  '名称': 'name',
  '类型': 'type',
  '时间': 'time',
  '端点': 'endpoint',
  '请求': 'request',
  '记录': 'record',
  '详情': 'details',
  '管理': 'management',
  '设置': 'settings',
  '配置': 'configuration',
  '登录': 'sign in',
  '退出': 'sign out',
  '默认': 'default',
  '当前': 'current',
  '全部': 'all',
  '总计': 'total',
  '输入': 'input',
  '输出': 'output',
  '费用': 'cost',
  '耗时': 'latency',
  '无': 'none',
  '个': '',
  '条': '',
  '页': 'page',
  '支持': 'supports',
  '模式': 'mode',
  '功能': 'features',
  '列表': 'list',
  '信息': 'information',
  '凭据': 'credentials',
  '安全': 'secure',
  '存储': 'storage',
  '设备': 'device',
  '上传': 'upload',
  '不会': 'will not',
  '需要': 'requires',
  '可以': 'can',
  '提供': 'provides',
  '查看': 'view',
  '自动': 'automatic',
  '手动': 'manual',
  '最新': 'latest',
  '立即': 'now',
  '下次': 'next time',
  '启动': 'launch',
  '保持': 'persist',
  '生效': 'take effect',
  '以及': 'and',
  '或者': 'or',
  '仅在': 'only in',
  '仅': 'only',
};

const phraseEntries = Object.entries(phraseEnglish).sort(([left], [right]) => right.length - left.length);

function compactEnglishFallback(value: string) {
  const rules: Array<[RegExp, string]> = [
    [/删除.*(吗|？)|确定删除|确认删除/, 'Delete this item?'],
    [/删除/, 'Delete'],
    [/保存.*(中|…|\.\.\.)/, 'Saving…'],
    [/保存/, 'Save'],
    [/(创建|新增|添加|生成).*(中|…|\.\.\.)/, 'Creating…'],
    [/(创建|新增|添加|生成)/, 'Create'],
    [/(加载|读取|查询).*(中|…|\.\.\.)/, 'Loading…'],
    [/(加载|读取|查询).*失败/, 'Load failed'],
    [/(加载|读取|查询)/, 'Load'],
    [/(检测|检查|测试).*(中|…|\.\.\.)/, 'Testing…'],
    [/(检测|检查|测试).*失败/, 'Test failed'],
    [/(检测|检查|测试)/, 'Test'],
    [/复制.*失败/, 'Copy failed'],
    [/复制/, 'Copy'],
    [/刷新.*(中|…|\.\.\.)/, 'Refreshing…'],
    [/刷新/, 'Refresh'],
    [/重置/, 'Reset'],
    [/恢复/, 'Restore'],
    [/撤销/, 'Revoke'],
    [/启用|开启/, 'Enable'],
    [/停用|禁用|关闭/, 'Disable'],
    [/打开/, 'Open'],
    [/登录.*失败/, 'Sign-in failed'],
    [/登录/, 'Sign in'],
    [/退出/, 'Sign out'],
    [/构建.*失败/, 'Build failed'],
    [/构建.*(中|排队)/, 'Building…'],
    [/构建/, 'Build'],
    [/提交.*(中|…|\.\.\.)/, 'Submitting…'],
    [/提交/, 'Submit'],
    [/成功|已完成|完成/, 'Done'],
    [/失败|错误|异常/, 'Failed'],
    [/等待|待处理|待调度|排队/, 'Pending'],
    [/暂停/, 'Paused'],
    [/处理中|已处理/, 'Processed'],
    [/确定|确认|继续|吗？|？/, 'Continue?'],
    [/API|接口|端点/, 'API settings'],
    [/密钥|Key/, 'API key'],
    [/GitHub|仓库|分支/, 'GitHub settings'],
    [/服务器|服务端|部署/, 'Server settings'],
    [/用户/, 'User settings'],
    [/账号/, 'Account settings'],
    [/分组/, 'Group settings'],
    [/代理/, 'Proxy settings'],
    [/模型|推理/, 'Model settings'],
    [/额度|余额|用量|消费|Token/, 'Usage'],
    [/请求|调用|响应/, 'Requests'],
    [/日志|审计/, 'Logs'],
    [/告警|运维|监控/, 'Monitoring'],
    [/备份|数据库/, 'Backups'],
    [/渠道/, 'Channels'],
    [/订阅|兑换码|优惠码|奖励|返利|推广|邀请/, 'Billing'],
    [/风控|审核|封禁/, 'Risk control'],
    [/系统|版本|升级|回滚|重启/, 'System'],
    [/搜索|筛选/, 'Search'],
    [/名称|标题/, 'Name'],
    [/状态/, 'Status'],
    [/时间|分钟|小时|天/, 'Time'],
    [/暂无|没有|未找到|未配置|未知|无/, 'None'],
  ];
  return rules.find(([pattern]) => pattern.test(value))?.[1] ?? 'Details';
}

export function translateText(value: string, language: 'zh' | 'en' = languageState.value) {
  if (language !== 'en' || !value) return value;
  const trimmed = value.trim();
  const exact = exactEnglish[trimmed];
  if (exact) return value.replace(value.trim(), exact);
  const isStaticCopy = staticChineseUICopy.has(trimmed) || staticChineseUITemplateFragments.some((fragment) => fragment.length > 1 && trimmed.includes(fragment));
  if (!isStaticCopy) return value;
  let translated = value;
  for (const [source, target] of phraseEntries) translated = translated.split(source).join(target);
  translated = translated
    .replace(/第\s*(\d+)\s*\/\s*(\d+)\s*page/g, 'Page $1 / $2')
    .replace(/共\s*(\d+)/g, '$1 total')
    .replace(/（/g, ' (')
    .replace(/）/g, ')')
    .replace(/，/g, ', ')
    .replace(/。/g, '. ')
    .replace(/：/g, ': ')
    .replace(/；/g, '; ')
    .replace(/·/g, ' · ')
    .replace(/\s{2,}/g, ' ')
    .trim();
  return /[\p{Script=Han}]/u.test(translated) ? compactEnglishFallback(value) : translated;
}

function translateNode(node: ReactNode, language: 'zh' | 'en'): ReactNode {
  if (typeof node === 'string') return translateText(node, language);
  if (Array.isArray(node)) return node.map((child) => translateNode(child, language));
  return node;
}

export function Text({ children, ...props }: TextProps) {
  const language = useSnapshot(languageState).value as 'zh' | 'en';
  return <NativeText {...props}>{translateNode(children, language)}</NativeText>;
}

export const TextInput = forwardRef<any, TextInputProps>(function LocalizedTextInput({ placeholder, ...props }, ref) {
  const language = useSnapshot(languageState).value as 'zh' | 'en';
  return <NativeTextInput ref={ref} placeholder={placeholder ? translateText(placeholder, language) : placeholder} {...props} />;
});

export function localizedAlert(title: string, message?: string, buttons?: AlertButton[], options?: AlertOptions) {
  const language = languageState.value;
  showThemedAlert({
    title: translateText(title, language),
    message: message ? translateText(message, language) : message,
    buttons: buttons?.map((button) => ({ ...button, text: button.text ? translateText(button.text, language) : button.text })),
    options,
  });
}
