import { forwardRef, type ReactNode } from 'react';
import { Text as NativeText, TextInput as NativeTextInput, type AlertButton, type AlertOptions, type TextInputProps, type TextProps } from 'react-native';

import { languageState } from '@/src/store/ui-preferences';
import { showThemedAlert } from '@/src/store/themed-alert';
import { staticChineseUICopy, staticChineseUITemplateFragments } from '@/src/generated/ui-copy';

const { useSnapshot } = require('valtio/react');

const exactEnglish: Record<string, string> = {
  '概览': 'Dashboard',
  '仪表盘': 'Dashboard',
  '用户': 'Users',
  '账号': 'Accounts',
  '分组': 'Groups',
  '服务器': 'Server',
  '设置': 'Settings',
  '保存': 'Save',
  '取消': 'Cancel',
  '删除': 'Delete',
  '编辑': 'Edit',
  '创建': 'Create',
  '新建': 'New',
  '复制': 'Copy',
  '关闭': 'Close',
  '完成': 'Done',
  '确认': 'Confirm',
  '返回': 'Back',
  '搜索': 'Search',
  '刷新': 'Refresh',
  '重试': 'Retry',
  '查询重置': 'Check resets',
  '可用次数：': 'Available: ',
  '当前没有可用次数，已禁用重置。': 'No resets available. Reset is disabled.',
  '启用': 'Enable',
  '停用': 'Disable',
  '隐藏': 'Hide',
  '显示': 'Show',
  '清除': 'Clear',
  '详情': 'Details',
  '收起': 'Collapse',
  '展开': 'Expand',
  '成功': 'Success',
  '失败': 'Failed',
  '正常': 'Healthy',
  '异常': 'Abnormal',
  '等待中': 'Queued',
  '执行中': 'Running',
  '处理中': 'Processing',
  '已完成': 'Completed',
  '已取消': 'Canceled',
  '已跳过': 'Skipped',
  '暂无数据': 'No data',
  '暂无记录': 'No records',
  '加载中…': 'Loading…',
  '保存中…': 'Saving…',
  '提交中…': 'Submitting…',
  '不限': 'Unlimited',
  '无': 'None',
  '全部': 'All',
  '是': 'Yes',
  '否': 'No',
  '中文': 'Chinese',
  '英文': 'English',
  '深色模式': 'Dark mode',
  '语言': 'Language',
  '退出账号': 'Sign out',
  '当前登录': 'Current session',
  'Admin Key 管理员': 'Admin Key administrator',
  '已登录用户': 'Signed-in user',
  '普通用户': 'User',
  '管理员': 'Administrator',
  '管理中心': 'Management center',
  '用户管理': 'User management',
  '账号管理': 'Account management',
  '分组管理': 'Group management',
  '代理管理': 'Proxy management',
  'IP 管理': 'IP management',
  'API 密钥': 'API keys',
  '使用记录': 'Usage logs',
  '运维监控': 'Operations monitor',
  '错误中心': 'Error center',
  '审计日志': 'Audit logs',
  '构建中心': 'Build center',
  '构建与同步': 'Build & sync',
  'AI 助手': 'AI assistant',
  'AI 配置': 'AI settings',
  '悬浮助手': 'Floating assistant',
  '管理悬浮助手、模型与修复配置': 'Manage the floating assistant, models, and repair settings.',
  '加载当前账号配置': 'Load current account configuration',
  '从当前登录的 Sub2API 服务器加载 OpenAI Base URL 和当前用户的活动密钥；多个密钥可选择其中一个。': 'Load the OpenAI Base URL and active keys for the current user from the signed-in Sub2API server. Select one when multiple keys are available.',
  '当前服务器 OpenAI Base URL': 'Current server OpenAI Base URL',
  '尚未连接 Sub2API 服务器': 'No Sub2API server connected',
  '正在加载当前账号密钥…': 'Loading current account keys…',
  '当前账号没有可用的活动密钥': 'No active keys are available for this account',
  '当前登录模式无法加载用户密钥': 'The current sign-in mode cannot load user keys',
  '刷新当前账号密钥': 'Refresh current account keys',
  '已选择': 'Selected',
  '选择': 'Select',
  '使用悬浮助手当前会话中的最新问题生成修复方案；创建 Draft PR 前仍会确认。': 'Generate a fix from the latest issue in the floating conversation. Draft PR creation still requires confirmation.',
  '删除历史对话': 'Delete conversation',
  '助手设置': 'Assistant settings',
  '收起助手设置': 'Hide assistant settings',
  '悬浮助手外观': 'Floating assistant appearance',
  '选择助手外观': 'Choose assistant appearance',
  '猫咪': 'Cat',
  '小狗': 'Dog',
  '狐狸': 'Fox',
  '兔子': 'Rabbit',
  '小精灵': 'Sprite',
  '迪迦奥特曼': 'Ultraman Tiga',
  '猪猪侠': 'GG Bond',
  '推理强度': 'Reasoning effort',
  '显示悬浮助手': 'Show floating assistant',
  'GitHub 配置': 'GitHub settings',
  '关于': 'About',
  '关于应用': 'About app',
  '版本、在线更新与开源信息': 'Version, online updates, and open-source information',
  '版本': 'Version',
  '升级提示': 'Update status',
  '自动检查 GitHub Release；下拉页面也可以重新检查。': 'Checks GitHub Releases automatically. Pull down to check again.',
  '正在检查 GitHub Release…': 'Checking GitHub Releases…',
  '暂时无法检查新版本': 'Unable to check for updates',
  '仓库尚未发布正式版本': 'No release is available yet',
  '当前已是最新版本': 'You are up to date',
  '重新检查版本': 'Check again',
  '正在检查…': 'Checking…',
  '打开 Release 页面': 'Open release page',
  '当前版本没有可用的 Android APK': 'No Android APK is available for this release',
  'App 内安装仅支持 Android': 'In-app installation is available on Android only',
  '无法访问下载目录': 'Unable to access the download directory',
  'APK 下载未完成，请重试': 'APK download did not finish. Try again.',
  '正在打开安装程序…': 'Opening installer…',
  '在 App 内下载并安装': 'Download and install in app',
  '将下载：': 'Download: ',
  '下载完成，正在打开系统安装程序': 'Download complete. Opening the system installer.',
  '正在下载更新': 'Downloading update',
  '所有 App 版本的升级提示已关闭，手动检查和下载仍可使用。': 'All app update alerts are off. Manual checks and downloads remain available.',
  '重新开启所有升级提示': 'Enable all update alerts',
  '已忽略此版本的升级提示：': 'Ignored update alert: ',
  '忽略此版本': 'Ignore this version',
  '关闭全部提示': 'Disable all alerts',
  '恢复此版本提示': 'Restore this version alert',
  'Expo 在线更新': 'Expo online update',
  '仅更新 JavaScript 与资源；原生依赖、权限或 Expo SDK 变化仍需安装新 APK。': 'Updates JavaScript and assets only. Native dependencies, permissions, or Expo SDK changes require a new APK.',
  '正式包启用 EAS Update 后，可以在这里下载在线更新并重启应用完成升级。': 'With EAS Update enabled, production builds can download an update here and restart to apply it.',
  '检查 Expo 在线更新': 'Check Expo update',
  '已是最新版本': 'You are up to date',
  '没有可用的 Expo 在线更新。': 'No Expo update is available.',
  '更新已下载': 'Update downloaded',
  '是否立即重新启动并应用更新？': 'Restart now to apply the update?',
  '稍后': 'Later',
  '立即重启': 'Restart now',
  '当前开发环境未启用 Expo 在线更新': 'Expo online updates are disabled in this development environment',
  '开源项目': 'Open source',
  '代码、发布版本、问题反馈与许可证信息。': 'Source code, releases, issue reporting, and license information.',
  '开源仓库': 'Source repository',
  '版本与 APK': 'Releases and APKs',
  '查看全部 GitHub Releases': 'View all GitHub Releases',
  '问题反馈': 'Issue tracker',
  '提交 Bug、建议或兼容性问题': 'Report bugs, suggestions, or compatibility issues',
  '查看本项目开源许可证': 'View the project license',
  '灵感来源': 'Acknowledgements',
  '感谢 ckken/sub2api-mobile 的开源成果': 'Thanks to the open-source work of ckken/sub2api-mobile',
  '更新与安全说明': 'Update and security notes',
  '请只从本项目 GitHub Releases 或你信任的构建渠道安装 APK。更新前建议保留服务器地址与登录信息。': 'Install APKs only from this project\'s GitHub Releases or a trusted build channel. Keep your server and sign-in details before updating.',
  'Android 会在 App 内下载 APK 并显示进度，完成后由系统安装程序确认安装；签名不一致时需要先卸载旧版。App 无法静默覆盖安装。': 'Android downloads the APK in the app with progress, then opens the system installer for confirmation. A signature mismatch requires uninstalling the old version. Silent replacement is not supported.',
  '查看安全策略': 'View security policy',
  '无法打开链接': 'Unable to open link',
  '更多管理': 'More administration',
  '当前登录、语言与 Sub2API 高级管理功能': 'Session, language, and advanced Sub2API management',
  '系统设置': 'System settings',
  '系统维护': 'System maintenance',
  '公告管理': 'Announcements',
  '订阅管理': 'Subscriptions',
  '兑换码': 'Redeem codes',
  '推广码': 'Promo codes',
  '备份管理': 'Backups',
  '备份与数据管理': 'Backup & data management',
  '操作审计': 'Audit trail',
  '全部 API': 'All APIs',
  '推广返利': 'Affiliate rewards',
  '渠道监控': 'Channel monitors',
  '编辑渠道': 'Edit channel',
  '新增渠道': 'Add channel',
  '合规确认': 'Compliance confirmation',
  'OAuth 授权': 'OAuth authorization',
  '优惠码': 'Promo codes',
  '提示词审计': 'Prompt audit',
  '新增代理': 'Add proxy',
  '编辑代理': 'Edit proxy',
  '风控中心': 'Risk control',
  '用户属性': 'User attributes',
  'API Key 分组': 'API key group',
  '用户详情': 'User details',
  '编辑用户': 'Edit user',
  '账号清单': 'Account list',
  '添加账号': 'Add account',
  '添加用户': 'Add user',
  '渠道管理': 'Channels',
  '流量策略': 'Traffic policies',
  '风险控制': 'Risk control',
  '定时测试': 'Scheduled tests',
  '账号定时刷新': 'Scheduled account refresh',
  '新建对话': 'New conversation',
  '历史对话': 'Conversation history',
  '完整对话': 'Full chat',
  '清空对话': 'Clear chat',
  '发送消息': 'Send message',
  '构建方式': 'Build provider',
  'GitHub 原生 APK': 'GitHub native APK',
  'EAS 云构建': 'EAS cloud build',
  '构建进度': 'Build progress',
  '安装依赖': 'Install dependencies',
  '配置': 'Configuration',
  '名称': 'Name',
  '状态': 'Status',
  '类型': 'Type',
  '平台': 'Platform',
  '模型': 'Model',
  '请求': 'Request',
  '请求模型': 'Requested model',
  '上游模型': 'Upstream model',
  '请求类型': 'Request type',
  '服务等级': 'Service tier',
  '计费模式': 'Billing mode',
  '端点': 'Endpoints',
  '时间': 'Time',
  '费用': 'Cost',
  '总耗时': 'Duration',
  '首字耗时': 'TTFT',
  '邮箱': 'Email',
  '密码': 'Password',
  '服务地址': 'Server URL',
  '当前用户创建的密钥': 'Keys created by the current user',
  '记住登录信息': 'Remember login information',
  '已记住的账号': 'Remembered accounts',
  '登录并连接': 'Sign in and connect',
  '邮箱密码': 'Email & password',
  '连接你的服务': 'Connect to your service',
  '支持邮箱密码登录和 Admin Key 管理模式。普通用户登录后只显示自助功能。': 'Sign in with email and password or use Admin Key administration mode. Standard users only see self-service features.',
  '退出后仍可从账号下拉列表快速登录': 'Use the account dropdown to sign in again after signing out',
  '切换后立即生效，并在下次启动时保持。': 'Changes apply immediately and persist across app launches.',
  '凭据保存在设备安全存储中，不会上传到移动端项目。': 'Credentials are stored securely on this device and are never uploaded to the mobile project.',
  '勾选后凭据保存在设备安全存储中，不会上传到移动端项目。': 'When enabled, credentials are stored securely on this device and are never uploaded.',
  'Web 端不持久化密码和 Admin Key。': 'The web app does not persist passwords or Admin Keys.',
  'Web 端不会保存密码或 Admin Key': 'The web app does not save passwords or Admin Keys',
  '登录页支持“网址 + 邮箱密码”和“网址 + Admin Key”两种方式。': 'The login page supports server URL with email/password or server URL with Admin Key.',
  '长按菜单并拖到目标位置，松手后自动保存。': 'Press and hold a menu item, drag it to the target position, then release to save.',
  '长按悬浮球可以关闭；关闭后可在这里重新打开。': 'Press and hold the floating assistant to disable it; enable it again here.',
  '长按悬浮助手可移动；靠边松手后会自动半隐藏。': 'Press and hold to move it. Release near an edge to dock it partially off-screen.',
  '关闭后可在这里重新打开。': 'Turn it back on here.',
  '在这里控制开关和外观；长按可移动，靠边松手后会自动半隐藏。': 'Control visibility and appearance here. Hold to move; release near an edge to dock.',
  '长按移动位置，靠边松手后会半隐藏；长按后点击右上角 × 可以关闭。': 'Press and hold to move it. Release near an edge to dock it partially off-screen. Tap the × after a long press to disable it.',
  '点击下拉快速登录': 'Open the dropdown for quick sign-in',
  '请输入服务器地址': 'Enter the server URL',
  '请输入邮箱和密码': 'Enter your email and password',
  '请输入 Admin Key': 'Enter the Admin Key',
  '正在检测当前服务是否可用...': 'Checking whether the current service is available…',
  '退出账号 / 更换登录方式': 'Sign out / change login method',
  '退出账号 / 切换账号': 'Sign out / switch account',
  '退出后可在登录页选择已记住的账号，或输入新的账号信息。': 'After signing out, choose a remembered account or enter another account on the sign-in page.',
  '这里只展示当前登录的服务器信息。如需新增或切换账号，请先退出，再到登录页选择或输入账号。': 'Only the current server session is shown here. To add or switch accounts, sign out and use the sign-in page.',
  '没有找到可作为默认账号的管理员。': 'No administrator account is available as the default account.',
  '当前账号还没有 API 密钥': 'This account has no API keys yet',
  '点击上方蓝色加号创建第一个密钥。': 'Tap the blue plus button above to create the first key.',
  '请调整搜索关键词。': 'Try a different search term.',
  '请立即复制保存。服务器可能只在创建时返回完整密钥。': 'Copy and save it now. The server may return the complete key only once.',
  '选择卡片中要显示的请求状态和诊断字段。': 'Select the request status and diagnostic fields shown on each card.',
  '按计划刷新启用账号的上游凭据': 'Refresh upstream credentials for enabled accounts on schedule',
  '根据队列和环境选择 EAS 或 GitHub 原生 APK 构建': 'Choose EAS or GitHub native APK builds based on queue and environment',
  '多会话 · Markdown · 页面级模型与推理设置': 'Multiple conversations · Markdown · Per-page model and reasoning settings',
  '查看 OpenAI 端点与当前账号的访问密钥': 'View the OpenAI endpoint and access keys for the current account',
  '集中查看所有密钥的访问白名单与黑名单': 'View access allowlists and blocklists for all keys',
  '打开用户管理': 'Open user management',
  '复制成功': 'Copied',
  '复制失败': 'Copy failed',
  '操作成功': 'Operation successful',
  '操作失败': 'Operation failed',
  '删除成功': 'Deleted',
  '删除失败': 'Delete failed',
  '保存成功': 'Saved',
  '保存失败': 'Save failed',
  '创建成功': 'Created',
  '登录失败': 'Sign-in failed',
  '恢复默认': 'Restore defaults',
  '账号状态已恢复。': 'Account status restored.',
  '账号状态恢复失败，请稍后重试。': 'Could not restore the account status. Try again later.',
  '知道了': 'Got it',
  '自定义状态显示': 'Customize displayed fields',
  '自定义菜单': 'Customize menu',
  '设为默认启动页面': 'Set as default start page',
  '取消默认启动页面': 'Clear default start page',
  '打开网站': 'Open website',
};

const phraseEnglish: Record<string, string> = {
  '当前服务端': 'current server',
  '当前账号': 'current account',
  '当前用户': 'current user',
  '当前页面': 'current page',
  '创建时间': 'created at',
  '更新时间': 'updated at',
  '最后更新': 'last updated',
  '登录信息': 'login information',
  '登录方式': 'sign-in method',
  '快速登录': 'quick sign-in',
  '安全存储': 'secure storage',
  '服务地址': 'server URL',
  '邮箱密码': 'email and password',
  '访问密钥': 'access key',
  '密钥名称': 'key name',
  '密钥状态': 'key status',
  '白名单': 'allowlist',
  '黑名单': 'blocklist',
  '所属分组': 'assigned group',
  '不绑定分组': 'no group',
  '请求记录': 'request records',
  '调用记录': 'usage records',
  '请求错误': 'request errors',
  '上游错误': 'upstream errors',
  '输入 Token': 'input tokens',
  '输出 Token': 'output tokens',
  '缓存写入': 'cache write',
  '缓存读取': 'cache read',
  '标准费用': 'standard cost',
  '实际费用': 'actual cost',
  '平均耗时': 'average latency',
  '上游账号': 'upstream account',
  '模型测试': 'model test',
  '质量检测': 'quality check',
  '连通测试': 'connectivity test',
  '定时刷新': 'scheduled refresh',
  '立即刷新': 'refresh now',
  '批量删除': 'delete selected',
  '批量操作': 'bulk actions',
  '全部删除': 'delete all',
  '打开浏览器': 'open browser',
  '打开任务': 'open run',
  '下载 APK': 'download APK',
  '构建 APK': 'build APK',
  '构建': 'build',
  '开始构建': 'start build',
  '构建结果': 'build result',
  '构建记录': 'build history',
  '构建仓库': 'build repository',
  '分支或标签': 'branch or tag',
  '原生构建': 'native build',
  '云端执行': 'runs in the cloud',
  '账号列表': 'account list',
  '用户列表': 'user list',
  '服务器列表': 'server list',
  '新增账号': 'add account',
  '添加账号': 'add account',
  '添加用户': 'add user',
  '新建密钥': 'create key',
  '编辑密钥': 'edit key',
  '删除密钥': 'delete key',
  '复制密钥': 'copy key',
  '搜索名称': 'search name',
  '恢复默认': 'restore defaults',
  '暂无': 'no',
  '正在': '',
  '已保存': 'saved',
  '已删除': 'deleted',
  '已创建': 'created',
  '已启用': 'enabled',
  '已停用': 'disabled',
  '请选择': 'please select',
  '请输入': 'please enter',
  '请先': 'please first',
  '请检查': 'please check',
  '点击': 'tap',
  '长按': 'press and hold',
  '打开': 'open',
  '选择': 'select',
  '切换': 'switch',
  '保存': 'save',
  '删除': 'delete',
  '编辑': 'edit',
  '创建': 'create',
  '新建': 'new',
  '复制': 'copy',
  '关闭': 'close',
  '取消': 'cancel',
  '确认': 'confirm',
  '返回': 'back',
  '搜索': 'search',
  '刷新': 'refresh',
  '启用': 'enable',
  '停用': 'disable',
  '隐藏': 'hide',
  '显示': 'show',
  '成功': 'success',
  '失败': 'failed',
  '错误': 'error',
  '用户': 'user',
  '账号': 'account',
  '分组': 'group',
  '密钥': 'key',
  '服务器': 'server',
  '代理': 'proxy',
  '模型': 'model',
  '平台': 'platform',
  '状态': 'status',
  '名称': 'name',
  '类型': 'type',
  '时间': 'time',
  '端点': 'endpoint',
  '请求': 'request',
  '记录': 'record',
  '详情': 'details',
  '管理': 'management',
  '设置': 'settings',
  '配置': 'configuration',
  '登录': 'sign in',
  '退出': 'sign out',
  '默认': 'default',
  '当前': 'current',
  '全部': 'all',
  '总计': 'total',
  '输入': 'input',
  '输出': 'output',
  '费用': 'cost',
  '耗时': 'latency',
  '无': 'none',
  '个': '',
  '条': '',
  '页': 'page',
  '支持': 'supports',
  '模式': 'mode',
  '功能': 'features',
  '列表': 'list',
  '信息': 'information',
  '凭据': 'credentials',
  '安全': 'secure',
  '存储': 'storage',
  '设备': 'device',
  '上传': 'upload',
  '不会': 'will not',
  '需要': 'requires',
  '可以': 'can',
  '提供': 'provides',
  '查看': 'view',
  '自动': 'automatic',
  '手动': 'manual',
  '最新': 'latest',
  '立即': 'now',
  '下次': 'next time',
  '启动': 'launch',
  '保持': 'persist',
  '生效': 'take effect',
  '以及': 'and',
  '或者': 'or',
  '仅在': 'only in',
  '仅': 'only',
};

const phraseEntries = Object.entries(phraseEnglish).sort(([left], [right]) => right.length - left.length);

function compactEnglishFallback(value: string) {
  const rules: Array<[RegExp, string]> = [
    [/删除.*(吗|？)|确定删除|确认删除/, 'Delete this item?'],
    [/删除/, 'Delete'],
    [/保存.*(中|…|\.\.\.)/, 'Saving…'],
    [/保存/, 'Save'],
    [/(创建|新增|添加|生成).*(中|…|\.\.\.)/, 'Creating…'],
    [/(创建|新增|添加|生成)/, 'Create'],
    [/(加载|读取|查询).*(中|…|\.\.\.)/, 'Loading…'],
    [/(加载|读取|查询).*失败/, 'Load failed'],
    [/(加载|读取|查询)/, 'Load'],
    [/(检测|检查|测试).*(中|…|\.\.\.)/, 'Testing…'],
    [/(检测|检查|测试).*失败/, 'Test failed'],
    [/(检测|检查|测试)/, 'Test'],
    [/复制.*失败/, 'Copy failed'],
    [/复制/, 'Copy'],
    [/刷新.*(中|…|\.\.\.)/, 'Refreshing…'],
    [/刷新/, 'Refresh'],
    [/重置/, 'Reset'],
    [/恢复/, 'Restore'],
    [/撤销/, 'Revoke'],
    [/启用|开启/, 'Enable'],
    [/停用|禁用|关闭/, 'Disable'],
    [/打开/, 'Open'],
    [/登录.*失败/, 'Sign-in failed'],
    [/登录/, 'Sign in'],
    [/退出/, 'Sign out'],
    [/构建.*失败/, 'Build failed'],
    [/构建.*(中|排队)/, 'Building…'],
    [/构建/, 'Build'],
    [/提交.*(中|…|\.\.\.)/, 'Submitting…'],
    [/提交/, 'Submit'],
    [/成功|已完成|完成/, 'Done'],
    [/失败|错误|异常/, 'Failed'],
    [/等待|待处理|待调度|排队/, 'Pending'],
    [/暂停/, 'Paused'],
    [/处理中|已处理/, 'Processed'],
    [/确定|确认|继续|吗？|？/, 'Continue?'],
    [/API|接口|端点/, 'API settings'],
    [/密钥|Key/, 'API key'],
    [/GitHub|仓库|分支/, 'GitHub settings'],
    [/服务器|服务端|部署/, 'Server settings'],
    [/用户/, 'User settings'],
    [/账号/, 'Account settings'],
    [/分组/, 'Group settings'],
    [/代理/, 'Proxy settings'],
    [/模型|推理/, 'Model settings'],
    [/额度|余额|用量|消费|Token/, 'Usage'],
    [/请求|调用|响应/, 'Requests'],
    [/日志|审计/, 'Logs'],
    [/告警|运维|监控/, 'Monitoring'],
    [/备份|数据库/, 'Backups'],
    [/渠道/, 'Channels'],
    [/订阅|兑换码|优惠码|奖励|返利|推广|邀请/, 'Billing'],
    [/风控|审核|封禁/, 'Risk control'],
    [/系统|版本|升级|回滚|重启/, 'System'],
    [/搜索|筛选/, 'Search'],
    [/名称|标题/, 'Name'],
    [/状态/, 'Status'],
    [/时间|分钟|小时|天/, 'Time'],
    [/暂无|没有|未找到|未配置|未知|无/, 'None'],
  ];
  return rules.find(([pattern]) => pattern.test(value))?.[1] ?? 'Details';
}

export function translateText(value: string, language: 'zh' | 'en' = languageState.value) {
  if (language !== 'en' || !value) return value;
  const trimmed = value.trim();
  const exact = exactEnglish[trimmed];
  if (exact) return value.replace(value.trim(), exact);
  const isStaticCopy = staticChineseUICopy.has(trimmed) || staticChineseUITemplateFragments.some((fragment) => fragment.length > 1 && trimmed.includes(fragment));
  if (!isStaticCopy) return value;
  let translated = value;
  for (const [source, target] of phraseEntries) translated = translated.split(source).join(target);
  translated = translated
    .replace(/第\s*(\d+)\s*\/\s*(\d+)\s*page/g, 'Page $1 / $2')
    .replace(/共\s*(\d+)/g, '$1 total')
    .replace(/（/g, ' (')
    .replace(/）/g, ')')
    .replace(/，/g, ', ')
    .replace(/。/g, '. ')
    .replace(/：/g, ': ')
    .replace(/；/g, '; ')
    .replace(/·/g, ' · ')
    .replace(/\s{2,}/g, ' ')
    .trim();
  return /[\p{Script=Han}]/u.test(translated) ? compactEnglishFallback(value) : translated;
}

function translateNode(node: ReactNode, language: 'zh' | 'en'): ReactNode {
  if (typeof node === 'string') return translateText(node, language);
  if (Array.isArray(node)) return node.map((child) => translateNode(child, language));
  return node;
}

export function Text({ children, ...props }: TextProps) {
  const language = useSnapshot(languageState).value as 'zh' | 'en';
  return <NativeText {...props}>{translateNode(children, language)}</NativeText>;
}

export const TextInput = forwardRef<any, TextInputProps>(function LocalizedTextInput({ placeholder, ...props }, ref) {
  const language = useSnapshot(languageState).value as 'zh' | 'en';
  return <NativeTextInput ref={ref} placeholder={placeholder ? translateText(placeholder, language) : placeholder} {...props} />;
});

export function localizedAlert(title: string, message?: string, buttons?: AlertButton[], options?: AlertOptions) {
  const language = languageState.value;
  showThemedAlert({
    title: translateText(title, language),
    message: message ? translateText(message, language) : message,
    buttons: buttons?.map((button) => ({ ...button, text: button.text ? translateText(button.text, language) : button.text })),
    options,
  });
}
