name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      profile:
        type: string
        required: true
        default: preview
        description: EAS build profile from eas.json

jobs:
  build_android:
    name: Build Android APK
    type: build
    params:
      platform: android
      profile: ${{ inputs.profile || 'preview' }}
